version: '3'
services:
  ms-sql-server:
    image: docker.io/b4rtosh/minimes:sql
    container_name: sql-server
    environment:
      SA_PASSWORD: "zaq1@WSX"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  server: 
    image: docker.io/b4rtosh/minimes:server
    container_name: minimes-server
    ports:
      - "5001:5001"
  front:
    image: docker.io/b4rtosh/minimes:front
    container_name: minimes-front
    ports:
      - "5174:5174"