name: Build and deploy to Azure
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Docker Builds
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Build Server Docker Image
        working-directory: ./ServerSide
        run: |
          docker build -t b4rtosh/minimes:server .
          docker push b4rtosh/minimes:server

      - name: Build Front Docker Image
        working-directory: ./ClientSide
        run: |
          docker build -t b4rtosh/minimes:front .
          docker push b4rtosh/minimes:front
      
      - name: Pull Database Docker Image
        run: |
          docker pull b4rtosh/minimes:sql
          
  deploy:
    defaults:
      run:
        working-directory: ./TerraformScripts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Init Terraform
        run: terraform init
        
      - name: Validate Terraform
        run: terraform validate

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Plan terraform
        run: terraform plan -out=tfplan
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_dockerhub_password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Deploy to Azure App Service
        run: terraform apply -auto-approve tfplan

